apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    annotations:
{{ toYaml . | indent 6 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8989
      protocol: TCP
  selector:
    app: {{ include "sonarr.name" . }}
    release: {{ .Release.Name }}